spring.application.name=cloud-consumer

server.port=8082

spring.cloud.nacos.discovery.server-addr=192.168.228.101:8848

management.endpoints.web.exposure.include=*

spring.cloud.sentinel.transport.dashboard=192.168.228.100:8080

